#
# Copyright (c) 2019, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  # this is the name of the Secret that will be generated, which will provide the wallet to connect to the DB
  name: atp-binding
spec:
  # The DB instance it is referring to
  instanceRef:
    name: atp-instance
  parametersFrom:
    # input parameters from the atp-secret, which contains the required walletPassword to extract the wallet
    - secretKeyRef:
        name: atp-secret
        key: walletPassword
