apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: demo

configurations:
- kustomizeconfig/custom.yaml

resources:
- ocir.Secret.yaml
- kafka.Secret.yaml
- atp-admin.Secret.yaml
- atp-user.Secret.yaml
- atp.Secret.yaml
- atp.ServiceBinding.yaml
- atp.ServiceInstance.yaml

- common.Namespace.yaml
- db-config.Job.yaml

- streaming.ServiceInstance.yaml
- streaming.ServiceBinding.yaml
