apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ1cy1hc2hidXJuLTEub2Npci5pbyI6eyJ1c2VybmFtZSI6Im9jaXNhdGVhbS9vY2lyX3B1c2hlcl8xNmE5Xzk0IiwicGFzc3dvcmQiOiJdY2lKSi5heHlfOH0jSlh1dnBhQSIsImVtYWlsIjoiamRvZUBhY21lLmNvbSIsImF1dGgiOiJiMk5wYzJGMFpXRnRMMjlqYVhKZmNIVnphR1Z5WHpFMllUbGZPVFE2WFdOcFNrb3VZWGg1WHpoOUkwcFlkWFp3WVVFPSJ9fX0=
kind: Secret
metadata:
  name: ocir-secret
type: kubernetes.io/dockerconfigjson
