apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: demo
build:
  tagPolicy:
    gitCommit: 
      variant: AbbrevCommitSha
  artifacts:
    - image: us-ashburn-1.ocir.io/ocisateam/demo/consumer
      context: src/consumer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**
            dest: .
    - image: us-ashburn-1.ocir.io/ocisateam/demo/producer
      context: src/producer
      sync:
        manual:
          - src: src/**
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us-ashburn-1.ocir.io/ocisateam/demo/web
      context: src/web
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**
            dest: .
    - image: us-ashburn-1.ocir.io/ocisateam/demo/db-config
      context: src/db-config
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**
            dest: .
portForward:
  - resourceType: deployment
    resourceName: dev-producer
    port: 5678
    localPort: 5678
  - resourceType: deployment
    resourceName: dev-consumer
    port: 5678
    localPort: 5679
  - resourceType: deployment
    resourceName: dev-web
    port: 5678
    localPort: 5680
# default deploy
deploy:
  kustomize:
    paths:
      - k8s/overlays/development
profiles:
  - name: dev
    deploy:
      kustomize:
        paths:
          - k8s/overlays/development
    patches:
      # add tag prefix to avoid rebuilding over the same hash
      - op: add
        path: /build/tagPolicy/gitCommit/prefix
        value: arl-
      # change the target image to use autoreload when code changes
      - op: add
        path: /build/artifacts/0/docker/target
        value: autoreload
      - op: add
        path: /build/artifacts/1/docker/target
        value: autoreload
      - op: add
        path: /build/artifacts/2/docker/target
        value: autoreload
      - op: add
        path: /build/artifacts/3/docker/target
        value: autoreload
  - name: debug
    deploy:
      kustomize:
        paths:
          - k8s/overlays/development
    patches:
      # add tag prefix to avoid rebuilding over the same hash
      - op: add
        path: /build/tagPolicy/gitCommit/prefix
        value: dbg-
      # change the target image to use debugger from skaffold 
      # requires that python
      - op: add
        path: /build/artifacts/0/docker/target
        value: debug
      - op: add
        path: /build/artifacts/1/docker/target
        value: debug
      - op: add
        path: /build/artifacts/2/docker/target
        value: debug
      - op: add
        path: /build/artifacts/3/docker/target
        value: debug
  - name: development
    deploy:
      kustomize:
        paths:
          - k8s/overlays/development
  - name: staging
    deploy:
      kustomize:
        paths:
          - k8s/overlays/staging
    patches:
      # add tag prefix to avoid rebuilding over the same hash
      - op: add
        path: /build/tagPolicy/gitCommit/prefix
        value: stage
  - name: production
    deploy:
      kustomize:
        paths:
          - k8s/overlays/production
