apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: demo
build:
  artifacts:
    - image: us-ashburn-1.ocir.io/ocisateam/demo/consumer
      context: src/consumer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**
            dest: .
    - image: us-ashburn-1.ocir.io/ocisateam/demo/producer
      context: src/producer
      sync:
        manual:
          - src: src/**
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us-ashburn-1.ocir.io/ocisateam/demo/web
      context: src/web
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**
            dest: .
    - image: us-ashburn-1.ocir.io/ocisateam/demo/db-config
      context: src/db-config
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**
            dest: .
portForward:
  - resourceType: deployment
    resourceName: dev-producer
    port: 5678
    localPort: 5678
  - resourceType: deployment
    resourceName: dev-consumer
    port: 5678
    localPort: 5679
  - resourceType: deployment
    resourceName: dev-web
    port: 5678
    localPort: 5680
# default deploy
deploy:
  kustomize:
    paths:
      - k8s/overlays/development
profiles:
  - name: dev
    deploy:
      kustomize:
        paths:
          - k8s/overlays/development
    patches:
      # change the target image to use autoreload when code changes
      - op: add
        path: /build/artifacts/0/docker/target
        value: autoreload
      - op: add
        path: /build/artifacts/1/docker/target
        value: autoreload
      - op: add
        path: /build/artifacts/2/docker/target
        value: autoreload
      - op: add
        path: /build/artifacts/3/docker/target
        value: autoreload
      # # add file sync to sync files to the live pod
      # - op: add
      #   path: /build/artifacts/0/docker/sync
      #   value: 
      #     manual:
      #     - src: src/**
      #       dest: .
      # copy same to the other artifacts that need it
      # - op: copy
      #   path: /build/artifacts/1/docker/target
      #   from: /build/artifacts/0/docker/target
      # - op: copy
      #   path: /build/artifacts/1/docker/sync
      #   from: /build/artifacts/0/docker/sync
      # - op: copy
      #   path: /build/artifacts/2/docker/target
      #   from: /build/artifacts/0/docker/target
      # - op: copy
      #   path: /build/artifacts/2/docker/sync
      #   from: /build/artifacts/0/docker/sync
      # - op: copy
      #   path: /build/artifacts/3/docker/target
      #   from: /build/artifacts/0/docker/target
      # - op: copy
      #   path: /build/artifacts/3/docker/sync
      #   from: /build/artifacts/0/docker/sync
  - name: debug
    deploy:
      kustomize:
        paths:
          - k8s/overlays/development
    patches:
      # change the target image to use debugger from skaffold 
      # requires that python
      - op: add
        path: /build/artifacts/0/docker/target
        value: debug
      - op: add
        path: /build/artifacts/1/docker/target
        value: debug
      - op: add
        path: /build/artifacts/2/docker/target
        value: debug
      - op: add
        path: /build/artifacts/3/docker/target
        value: debug
      # # add file sync to sync files to the live pod
      # - op: add
      #   path: /build/artifacts/0/docker/sync
      #   value: 
      #     manual:
      #     - src: src/**
      #       dest: .
      # copy same to the other artifacts that need it
      # - op: copy
      #   path: /build/artifacts/1/docker/target
      #   from: /build/artifacts/0/docker/target
      # - op: copy
      #   path: /build/artifacts/1/docker/sync
      #   from: /build/artifacts/0/docker/sync
      # - op: copy
      #   path: /build/artifacts/2/docker/target
      #   from: /build/artifacts/0/docker/target
      # - op: copy
      #   path: /build/artifacts/2/docker/sync
      #   from: /build/artifacts/0/docker/sync
      # - op: copy
      #   path: /build/artifacts/3/docker/target
      #   from: /build/artifacts/0/docker/target
      # - op: copy
      #   path: /build/artifacts/3/docker/sync
      #   from: /build/artifacts/0/docker/sync
  - name: development
    deploy:
      kustomize:
        paths:
          - k8s/overlays/development
  - name: staging
    deploy:
      kustomize:
        paths:
          - k8s/overlays/staging
  - name: prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/production
