
# Config map for common environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: db
data:
  ENVIRONMENT: PRODUCTION
  # must match the dbName value in the atp.ServiceInstance, 
  # with one of _tp, _tpurgent, _medium, _high, _low
  TNS_NAME: prodk8satp_tp
