namePrefix: dev-
commonLabels:
  environment: development
  org: acmeCorporation
# this namespace name is the composed name using the ns name and the prefix
namespace: dev-ns

bases:
- ../../base

patchesStrategicMerge:
- common.ConfigMap.yaml
- web.Deployment.yaml
- streaming.ServiceBinding.yaml
- streaming.ServiceInstance.yaml
