namePrefix: dev-
commonLabels:
  environment: development
  org: acmeCorporation

# this namespace name is the composed name using the ns name and the prefix
namespace: dev-ns

bases:
- ../../base

configMapGenerator:
# common.ConfigMap.yaml
- name: common
  behavior: merge
  literals: 
  - ENVIRONMENT=DEVELOPMENT
  - TNS_NAME=devk8satp_tp  # must match the dbName in atp.ServiceInstance.patch.yaml with the service name suffix
# kafka.ConfigMap.yaml
- name: kafka
  behavior: merge
  literals: 
  - TOPIC=dev-datastream

patchesStrategicMerge:
- consumer.Deployment.yaml
- producer.Deployment.yaml
- atp.ServiceInstance.patch.yaml
