apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: demo

resources:
- web.Deployment.yaml
- web.Service.yaml
- web.HorizontalPodAutoscaler.yaml

- consumer.Deployment.yaml
- consumer.HorizontalPodAutoscaler.yaml
- producer.Deployment.yaml
