apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    use_streaming: 'yes'
    use_ocir: 'yes'
spec:
  replicas: 1
  strategy: 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      service: producer
  template:
    metadata:
      labels:
        service: producer
    spec:
      imagePullSecrets: []
      containers:
      - name: producer
        # image: us-ashburn-1.ocir.io/ocisateam/demo/producer:latest
        image: producer:latest
        imagePullPolicy: Always
        env: 
          - name: NS_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        envFrom: []
        # kafka creds will be injected here
        resources:
          limits:
            memory: "100Mi"
            cpu: "250m"
          requests:
            memory: "100Mi"
            cpu: "250m"
