namePrefix: prod-
commonLabels:
  environment: production
  org: acmeCorporation

# this namespace name is the composed name using the ns name and the prefix
namespace: prod-ns

bases:
- ../../base

configMapGenerator:
# common.ConfigMap.yaml
- name: common
  behavior: merge
  literals: 
  - ENVIRONMENT=PRODUCTION
  - TNS_NAME=prodk8satp_tp  # must match the dbName in atp.ServiceInstance.patch.yaml with the service name suffix
# kafka.ConfigMap.yaml
- name: kafka
  behavior: merge
  literals: 
  - TOPIC=prod-datastream


patchesStrategicMerge:
- consumer.Deployment.yaml
- producer.Deployment.yaml
- atp.ServiceInstance.patch.yaml
