namePrefix: prod-
commonLabels:
  environment: production
  org: acmeCorporation
namespace: prod-ns

bases:
- ../../base

patchesStrategicMerge:
- common.ConfigMap.yaml
- web.Deployment.yaml
- streaming.ServiceBinding.yaml
- streaming.ServiceInstance.yaml
