apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: consumer
  template:
    metadata:
      labels:
        service: consumer
    spec:
      containers:
      - name: consumer
        image: us-ashburn-1.ocir.io/ocisateam/demo/consumer:1.0.11
        env:
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: KAFKA_BROKERS
        - name: TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: TOPIC
        - name: KAFKA_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka-secret
              key: KAFKA_USERNAME
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secret
              key: KAFKA_PASSWORD
      imagePullSecrets:
        - name: ocir-secret