apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# metadata:
#   name: base
namespace: dev

commonLabels:
  app: demo
  environment: development

resources:
- common.ConfigMap.yaml
- common.Namespace.yaml
- redis.Deployment.yaml
- redis.Service.yaml
- streaming.ServiceBinding.yaml
- streaming.ServiceInstance.yaml
- kafka.ConfigMap.yaml
- consumer.Deployment.yaml
- producer.Deployment.yaml
- web.Deployment.yaml
- web.Service.yaml
- web.ConfigMap.yaml
