apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

commonLabels:
  app: demo

configurations:
- kustomizeconfig/custom.yaml

resources:
- common.ConfigMap.yaml
# - common.Namespace.yaml
# - redis.Deployment.yaml
# - redis.Service.yaml
# - web.Deployment.yaml
# - web.Service.yaml
# - web.ConfigMap.yaml

- consumer.Deployment.yaml
- producer.Deployment.yaml

- kafka.ConfigMap.yaml
- streaming.ServiceInstance.yaml
- streaming.ServiceBinding.yaml

- atp-user.Secret.yaml
- atp.Secret.yaml
- atp.ServiceBinding.yaml
- atp.ServiceInstance.yaml
