apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base

commonLabels:
  app: demo
  environment: development

resources:
- common.ConfigMap.yaml
- web.Deployment.yaml
- web.Service.yaml
- web.ConfigMap.yaml
- redis.Deployment.yaml
- redis.Service.yaml
