apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    use_streaming: 'yes'
spec:
  replicas: 1
  strategy: 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      service: producer
  template:
    metadata:
      labels:
        service: producer
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
      - name: producer
        image: us-ashburn-1.ocir.io/ocisateam/demo/producer:latest
        imagePullPolicy: Always
        env: 
          - name: LOG_LEVEL
            value: INFO
        envFrom: []
        # kafka creds will be injected here
        resources:
          limits:
            memory: "20Mi"
            cpu: "50m"
          requests:
            memory: "20Mi"
            cpu: "50m"
