apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - name: web
        image: us-ashburn-1.ocir.io/ocisateam/demo/web:latest
        ports:
          - containerPort: 80
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: web
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: web
              key: REDIS_PORT
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: common
              key: ENVIRONMENT
      imagePullSecrets:
        - name: ocir-secret
