namePrefix: staging-
commonLabels:
  environment: staging
  org: acmeCorporation
namespace: staging-ns
bases:
- ../../base

patchesStrategicMerge:
- common.ConfigMap.yaml
- web.Deployment.yaml
- streaming.ServiceBinding.yaml
- streaming.ServiceInstance.yaml
